services:
  - type: web
    name: demo-container
    rootDir: demo-container
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors *"
