static_sites:
  - name: demo-container
    buildCommand: cd demo-container && npm install && npm run build
    staticPublishPath: demo-container/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors *"
